title: Jekyll Sandbox
email: triyuga@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  If you're looking for information about me, you might want
  to check out my CV on <a href=https://stackoverflow.com/cv/mchirico>cv/mchirico.</a>
theme: jekyll-theme-minimal
